### ISSUE TITLE
Update Position

### ISSUE THREAD

**Issue by michaelsakharov** [Nition/UnityOctree#18]
No way to update the position of an octree, has an initial position but no way to change once set?

**Comment by Nition** [comment]
The root node does actually move when the octree grows, but that's more of a side effect and apart from that you're correct unfortunately. The octree can grow an shrink but it's designed at the moment with the intention that the root basically stays in place.

I have used it on moving objects myself, by translating the position and rotation of the object into a zero-based one before passing it into the octree. But that only works if _everything_ in your octree is moving together in the same way so it's a pretty special case.

**Comment by michaelsakharov** [comment]
Actually, thats perfect, I'm developing a large scale space game and using this for the stars. Got it all working but my floating origin does not work with this. The galaxy and all points inside move with the octree as the player moves. Could you guide me in the direction of implementing this?

**Comment by Nition** [comment]
Yeah. I'm not sure how well any of this will all work if you're dealing with big universe-scale stuff with potential floating point precision issues and all that, but what I'm talking about is just adjusting everything to pretend the origin is at zero whenever you interact with the octree.

So you'd add your planets etc to the octree with the origin subtracted - literally just `position - origin`, or if rotation is involved:

```
public static Vector3 TransformPoint(Vector3 point, Transform origin) {
	return Quaternion.Inverse(origin.rotation) * (point - origin.position);
}
```

Or for bounds (ignoring rotation here):

```
public static Bounds TransformBounds(Bounds bounds, Vector3 origin) {
	// Note: Bounds are a struct, so changing bounds here does not modify the input
	bounds.center = bounds.center - origin;
	return bounds;
}
```

There are some slightly tricky bits if you need to transform the _rotation_ of Bounds as well, but I'm guessing you only move your universe's origin and don't rotate the whole universe as well, so that's hopefully not an issue!

Then when you want to interact with the octree, you need to transform any positions into "zero origin" position as well. e.g. Say you want to raycast from your player's ship against the octree, subtract the ray's origin position from the world origin again as above and then call IsColliding as usual.

**Comment by michaelsakharov** [comment]
Hmm, any way to get this to work correctly? with Floating Origin?

**Comment by Nition** [comment]
Maybe move the offset into the octree itself.

Add an origin variable to the octree that matches your world's one. Have everything in the octree at its actual (zero origin) position. But when you call IsColliding or whatever, have it subtract the current origin from every position calculation internally - then it'd be acting just like it's in local space.

Although I feel like it's still going to be tricky if your whole universe is in one octree no matter how you adjust the origin. Because no matter where your origin is, there'll be _some_ stuff in there that's super far away, right?

**Comment by michaelsakharov** [comment]
Well I actually only have 1 galaxy, but it's about 1,000,000,000,000,000 meters across, got it all working great with floating origin, but I need to get the nearest star to the player, that's where this octree comes in. but yeah, there are things really far away from the origin.

**Comment by Nition** [comment]
Hmm. You could always update the octree to use a higher precision - doubles instead of floats - but actually I have a better idea. Stars are pretty far apart, so it shouldn't matter too much if you lose precision on the low end: What if you just pass everything in but with its position divided by like a million or whatever? Then pass in the player's position also divided by the same amount and origin-adjusted. Like a tiny model of the galaxy to check against.

**Comment by michaelsakharov** [comment]
Hmm I see that you mean, Dividing a replica of galaxy down to a smaller scale which the octree can handle without the need for floating precision? Then get whichever star is closest to the player, then rescale it and place the solar system? But it would probably lag a bit dividing the position of millions of stars?

**Comment by Nition** [comment]
The stars don't move though, right? So you'd just do all the division and adding on load. _Millions_ of entries in my humble octree though? That's going to be interesting...

**Comment by michaelsakharov** [comment]
Well I got 8 million points in your octree without any noticable fps drop!

**Comment by michaelsakharov** [comment]
Gave it a shot, seems to be working, but a massive fps drop, 70 fps down to 0.5 - 1 fps! Thought of threading it, but then it may go out of sync.

**Comment by michaelsakharov** [comment]
Actually my fps only seems to drop when im near the world origin... odd

**Comment by michaelsakharov** [comment]
Nvm fixed the performance.

**Comment by michaelsakharov** [comment]
Looks like its working!

**Comment by michaelsakharov** [comment]
Would just like to note: Your amazing :D Im using that method for more then just the octree now, great way to work around floating origin!

**Comment by Nition** [comment]
Cool. Just probably keep in mind that it'll run into issues if you have things really close together, since it'll get lost in the precision limits. I figured stars were a good candidate since they'll usually be far apart.
