### ISSUE TITLE
ShrinkIfPossible method bug

### ISSUE THREAD

**Issue by kayler-renslow** [Nition/UnityOctree#19]
The implementation of `ShrinkIfPossible(float minLength)` requires that there is only 1 child in the node, as mentioned in the documentation. However, the current implementation makes no such check and in some instances of node removal, some nodes that shouldn't be removed end of getting implicitly removed (this is basically a memory leak).

The fix is simple:

```
public BoundsOctreeNode<T> ShrinkIfPossible(float minLength) {
	// NEW CODE
	if (objects.Count >= 2) {
		return this;
	}
	// END NEW CODE

	if (BaseLength < (2 * minLength)) {
		return this;
	}
	if (objects.Count == 0 && (children == null || children.Length == 0)) {
		return this;
	}
//.... the rest of the code

```

**Comment by Nition** [comment]
Thanks, I haven't looked at the code for a while to be honest so I might be misreading how shrink actually works, but I think:

You're checking `objects.Count` there but your comment implies you meant to check `children.Count`? There are always either zero or eight children, so you'd have to check `children[i].HasAnyObjects()` for that (which the method does later).

For objects, it should be able to be shrunk if all objects in the node are within one octant - so I think that could be >1 object if they're in the right place.

**Comment by kayler-renslow** [comment]
I think I'm a bit confused as well. I was thinking originally that objects and children were parallel lists/arrays. 

 However, adding this check fixed the issue. I think what really is the problem then is that when the node shrinks, it isn't bringing the objects with it.

Therefore querying for the objects that were accidentally removed ends of empty.

**Comment by kayler-renslow** [comment]
The problem is that the code won't allow a shrink when a child has elements. When the children are all empty, the root node gets replaced with its child. However, the code fails to recognize the edge case that the root node might have content.

If the root node has content but the children do not, the root gets swapped for a child, but the child doesn't get the old root node's data, thus a memory "leak" takes place.

 I hope that clarifies what I'm saying. Octrees are new to me.

**Comment by Nition** [comment]
Technically I don't think that should ever happen, because if the objects in a node _can_ fit into a single child of that node, and the node has children, they should be in the child already. The only objects left in the parent node should be ones that can't fit into a single child, which should stop it from shrinking anyway. 

And indeed I can't get that situation to happen in my test project. Can you try something for me? Put a print or a breakpoint in, something like this:

```
public BoundsOctreeNode<T> ShrinkIfPossible(float minLength) {

...

// No objects in entire octree
if (bestFit == -1) {
	return this;
}

// We have children. Use the appropriate child as the new root node
if (objects.Count > 0) Debug.Log("This shouldn't happen..."); // Add this
return children[bestFit];
}
```

Remove your `if (objects.Count >= 2)` fix from the start of the method. Does my extra line ever trigger for you?

**Comment by Nition** [comment]
Technically I don't think that should ever happen, because if the objects in a node _can_ fit into a single child of that node, and the node has children, they should be in the child already. The only objects left in the parent node should be ones that can't fit into a single child, which should stop it from shrinking anyway. 

And indeed I can't get that situation to happen in my test project. But I do see a potential issue, where it looks like if the node has **no** children but all its objects could fit into one child (that can happen if it has less than numObjectsAllowed), it can still end up returning `children[bestFit];` even though children should be null.

Can you try something for me? Put a print or a breakpoint in, something like this:

```
public BoundsOctreeNode<T> ShrinkIfPossible(float minLength) {

	... // Rest of the code

	// No objects in entire octree
	if (bestFit == -1) {
		return this;
	}

	// We have children. Use the appropriate child as the new root node
	if (objects.Count > 0) Debug.Log("Does this ever happen?"); // Add this bit
	return children[bestFit];
}
```

Remove your `if (objects.Count >= 2)` fix from the start of the method. Does my extra line ever trigger for you?

**Comment by kayler-renslow** [comment]
My understanding of octrees definitely can be better. It appears there is no issue at all and I was misunderstanding how the querying works (GetColliding()). Everything is good. :D
