### ISSUE TITLE
Index Out of Range in "ShrinkIfPossible"

### ISSUE THREAD

**Issue by JasonRTBond** [Nition/UnityOctree#22]
`    // We have children. Use the appropriate child as the new root node
    return children[bestFit];`

I'm hitting a case where "bestFit" can still be -1 at this line. The culprit appears to be this case:

 objects.Count = 0
 children.Length = 8

**Comment by Nition** [comment]
Obviously I haven't tested ShrinkIfPossible enough in the past - thanks for finding this and the other bug you found earlier, but sorry you're getting them.

So the situation you're describing is, you have an empty node (`objects.Count = 0`) with children (if there are children, there are always 8), and the children are all empty as well, or else bestFit couldn't still be -1.

I'm afraid I don't have the time to look into this properly at the moment, but I can help maybe.

I'd double check that `children[i].HasAnyObjects()` is really returning false 8 times in `ShrinkIfPossible`, in that children loop.

Something is going wrong somewhere earlier, because having an empty object with all empty children should never happen. When `Remove` is called, it checks `ShouldMerge`. If the children are all empty as it seems in your case, ShouldMerge should have already collapsed the children into the base node before ShrinkIfPossible is called, and children should be null.

**Comment by Nition** [comment]
Should now be fixed.
