### ISSUE TITLE
Nodes who have children shouldn't contain any OctreeObject

### ISSUE THREAD

**Issue by henryxrl** [Nition/UnityOctree#28]
Hi Nition,
If I understand the code correctly, when adding an object into the octree, if the current node contains enough object, we create children and move all the objects a level deeper. But in "GetNearby" function, I found that if a node has children, it STILL contains all the objects. Its children will have copies of the same objects. Could you please look into this? Or am I misunderstanding anything here?

**Comment by Nition** [comment]
Hey, I haven't got time to check this out properly at the moment unfortunately but I just want to say I have read it and I'll have a look when I can.

Objects _should_ be getting removed from the parent when they're added to the children, yeah. I see the code that should be doing it in SubAdd:
`objects.Remove(existingObj); // Remove from here`

If they're hanging around, something's going wrong somewhere.

**Comment by Nition** [comment]
I fixed a very similar bug just recently. Could you please update and see if your bug is now fixed? As you say, nodes who have children shouldn't contain any octree objects, at least in the Point octree. In the Bounds octree, objects that don't fit into a child (crossing the border between two children) will stay in the parent.

**Comment by Nition** [comment]
Closing this since it's been 10 days, but feel free to respond if you're still getting the issue.
