### ISSUE TITLE
ShrinkIfPossible bug

### ISSUE THREAD

**Issue by davidebarbieri** [Nition/UnityOctree#29]
Hi,

the ShrinkIfPossible method is called and possibly a child node becomes root
because all the node's objects can fit the child octant.
Where the objects of the previous root go?
Shouldn't they be added to the child node in the ShrinkIfPossible method?

**Comment by Nition** [comment]
Correct me if I'm wrong, but I think in the case that you can shrink into a child, the root is always empty already.

If the root has children, it will have already moved any objects that can fit into one of those children into the appropriate child, so the only objects left in the root will be those that span multiple children. If any objects span multiple children, we cannot shrink. Therefore if we can shrink into a child, the root is already empty.

**Comment by davidebarbieri** [comment]
Yeah, I've a lot of cases where I add multiple objects, then remove some objects and some others
are lost. By changing the ShrinkIfPossible, in a way that the root moves its own objects to the child, then the problem is solved. I'm sorry I can't send you the test code, but if you just add and remove nodes randomly the bug will come up quite often.

I'm using the PointOctree, I don't know if the problem is the same in the BoundOctree.
I'm just using Add/Remove/GetNearby methods.

PointOctree ShrinkIfPossible checks for root's objects and supports the case all the objects fall
in the same octant, why it would check this if it can't never be this case?

For example, there is the case you insert NUM_OBJECTS_ALLOWED objects which fall in the same octant. The child node is created. Then, you add another object, and the SubAdd will add it to the root.
If you shrink, the root will lose that object.

**Comment by Nition** [comment]
Ah, thanks for that, I see the bug is now. Sorry about this because it's a bit of a nasty bug.

I think I had assumed at the time (I wrote this code a few years ago now) that everything should always go into its smallest possible child. If NUM_OBJECTS_ALLOWED was reached and minSize was also reached, the objects would pile up in the deepest child - not start to accumulate in the root. I think that root objects check in ShrinkIfPossible was just meant to shrink a root with no children into the size of a child if it could be done.

But I see that's not how it actually works, and maybe that's not how it should work either. One the root passes its objects down into children, it empties out, so the NUM_OBJECTS_ALLOWED  check in SubAdd passes and objects start getting added to the root again.

I'll have a look again at what other octrees do and do a fix one way or another. Unfortunately I can't right now. Hopefully in the next week or so.

**Comment by davidebarbieri** [comment]
Ok, don't worry. Take your time :) Thanks.

**Comment by Nition** [comment]
Update and try now. Objects should now always reside in the deepest possible child, which should fix the shrink losing objects bug.

**Comment by davidebarbieri** [comment]
Thanks I'll try ASAP

**Comment by Nition** [comment]
Nice find, thank you for the fix. I've checked it over and just pushed it to GitHub now, adding the same fix to BoundsOctree as well. Also, nice trick using BestFitChild in Grow, removing the need for the extra child finding method.

I'm embarrassed about these dumb errors in the code but I'm glad they're getting found and fixed.

Do your fixes cover all the issues you mentioned about, or is there still a problem somewhere else with PointOctree.Remove?

**Comment by rswa** [comment]
yes, the issues be fixed .
