### ISSUE TITLE
Main difference

### ISSUE THREAD

**Issue by tynic** [Nition/UnityOctree#7]
Hello, thanks a lot for your example!

I have a question. What's the main difference between bound or point-based octree? I've read your documentation (and it's great) and code (sorry, I'm not good in C# so much) but I can't see the purpose...

Point-based octree seems better to me but what are the restrictions?

Thanks for your reply. Good work!

**Comment by Nition** [comment]
Hi

The point tree is points - like, things that take up no space.
The bounds tree is cuboid shapes - cubes and 3D rectangles that take up space.

A bounds octree is a little more complicated to fit into octree spaces than points, because bounds take up some amount of space. One bounds could cross the boundary between two different nodes in the octree.

Basically if you have points, put them in the points tree, but if you have 3D things that take up space, put them in the bounds tree.

Hope that helps a bit.
